In [1]:
import pandas as pd

In [21]:
df = pd.read_csv('data.csv', dtype='str')
df

,id,person_info,label
0,460790679,2024-12-20 15:51:43$%$45V$%$天能$%$72Ah,电池额定电压/额定容量与填写信息不一致
1,460796201,2024-04-09 08:23:10$%$72V$%$超威$%$60Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求
2,460802483,2024-04-08 17:59:48$%$60V$%$超威$%$60Ah,非电池相关信息图片
3,460797429,2022-02-04 13:06:43$%$48V$%$星恒$%$24Ah,非规范电池信息图片|||电池生产日期与填写信息不一致
4,460810274,2025-03-02 10:11:58$%$72V$%$天能$%$32Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求
...,...,...,...
195,460794253,2023-03-04 09:22:59$%$60V$%$其他品牌:安耐行$%$80Ah,非规范电池信息图片
196,460797400,2021-12-13 10:00:23$%$60V$%$其他品牌:劲锐科智能锂电$%$50Ah,非规范电池信息图片
197,460798293,2024-07-03 12:24:50$%$48V$%$其他品牌:博邦$%$60Ah,非规范电池信息图片
198,460794561,2024-11-30 14:50:13$%$72V$%$其他品牌:众科$%$60Ah,使用电池规格严重超标，不符合国标要求
199,460796351,2022-02-11 12:39:41$%$72V$%$其他品牌:青棵锂电$%$55Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           200 non-null    object
 1   person_info  200 non-null    object
 2   label        198 non-null    object
dtypes: object(3)
memory usage: 4.8+ KB

In [23]:
all_label = [str(i).split('|||') for i in df['label'].tolist()]
all_set_label = set()
for i in all_label:
    for j in i:
        all_set_label.add(j)

In [24]:
all_set_label

{'nan',
 '使用电池不符合规范',
 '使用电池规格严重超标，不符合国标要求',
 '电池品牌图片与填写品牌信息不一致',
 '电池生产日期与填写信息不一致',
 '电池额定电压/额定容量与填写信息不一致',
 '非电池相关信息图片',
 '非规范电池信息图片'}

In [25]:
def get_response(data):
    res = {'电池合规检测':'通过', '电池规格检测':'通过', '品牌检测':'通过', '日期检测':'通过', '电压检测':'通过', '图片规范检测':'通过'}
    data = str(data)
    for i in  data.split('|||'):
        if i == '使用电池不符合规范':
            res['电池合规检测'] = '驳回，使用电池不符合规范'
        elif i == '使用电池规格严重超标，不符合国标要求':
            res['电池规格检测'] = '驳回，使用电池规格严重超标，不符合国标要求'
        elif i == '电池品牌图片与填写品牌信息不一致':
            res['品牌检测'] = '驳回，电池品牌图片与填写品牌信息不一致'
        elif i == '电池生产日期与填写信息不一致':
            res['日期检测'] = '驳回，电池生产日期与填写信息不一致'
        elif i == '电池额定电压/额定容量与填写信息不一致':
            res['电压检测'] = '驳回，电池额定电压/额定容量与填写信息不一致'
        elif i == '非电池相关信息图片' or i == '非规范电池信息图片':
            res['图片规范检测'] = '驳回，上传图片信息非电池相关'
    return str(res)

In [26]:
df['response'] = df['label'].apply(lambda x: get_response(x))
df

,id,person_info,label,response
0,460790679,2024-12-20 15:51:43$%$45V$%$天能$%$72Ah,电池额定电压/额定容量与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',..."
1,460796201,2024-04-09 08:23:10$%$72V$%$超威$%$60Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国..."
2,460802483,2024-04-08 17:59:48$%$60V$%$超威$%$60Ah,非电池相关信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',..."
3,460797429,2022-02-04 13:06:43$%$48V$%$星恒$%$24Ah,非规范电池信息图片|||电池生产日期与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',..."
4,460810274,2025-03-02 10:11:58$%$72V$%$天能$%$32Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国..."
...,...,...,...,...
195,460794253,2023-03-04 09:22:59$%$60V$%$其他品牌:安耐行$%$80Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',..."
196,460797400,2021-12-13 10:00:23$%$60V$%$其他品牌:劲锐科智能锂电$%$50Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',..."
197,460798293,2024-07-03 12:24:50$%$48V$%$其他品牌:博邦$%$60Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',..."
198,460794561,2024-11-30 14:50:13$%$72V$%$其他品牌:众科$%$60Ah,使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国..."
199,460796351,2022-02-11 12:39:41$%$72V$%$其他品牌:青棵锂电$%$55Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国..."

In [27]:
def get_query(data):
    times,pv,brand,pi = data.split('$%$')
    prompt = f"""
    请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：
    1. 根据输入的品牌名称：{brand}与第一张图片中的品牌进行信息匹配
    2. 根据输入的电池的生产日期:{times}与第二张图片中的生成日期进行信息匹配
    3. 根据输入的电池的电压:{pv}、电流：{pi}与第二张图片中的电压、电流进行信息匹配
    4. 判断上传的两张图片是否与电池相关的图片、以及清晰度
    根据匹配的结果，如果符合要求则输出：通过，不符合则输出，驳回以及驳回的标签
    """.strip() 
    return prompt

In [28]:
df['query'] = df['person_info'].apply(lambda x: get_query(x))

In [29]:
import os 
all_id = set([i.split('_')[0].split('.')[0] for i in os.listdir('./brand_new/')]) & set([i.split('_')[0].split('.')[0] for i in os.listdir('./charge_new/')])
all_id

{'',
 '460790592',
 '460790679',
 '460790794',
 '460790811',
 '460790888',
 '460790988',
 '460791010',
 '460791012',
 '460791273',
 '460791308',
 '460791586',
 '460791592',
 '460791881',
 '460791920',
 '460792182',
 '460792269',
 '460793319',
 '460793628',
 '460793740',
 '460793743',
 '460793768',
 '460793985',
 '460794180',
 '460794212',
 '460794253',
 '460794256',
 '460794288',
 '460794309',
 '460794316',
 '460794561',
 '460794747',
 '460794832',
 '460795013',
 '460795016',
 '460795028',
 '460795066',
 '460795258',
 '460795418',
 '460795691',
 '460795692',
 '460795777',
 '460795848',
 '460795869',
 '460795921',
 '460796007',
 '460796015',
 '460796109',
 '460796201',
 '460796287',
 '460796318',
 '460796353',
 '460796492',
 '460796726',
 '460796842',
 '460796886',
 '460796954',
 '460797063',
 '460797078',
 '460797091',
 '460797360',
 '460797400',
 '460797429',
 '460797511',
 '460797577',
 '460798030',
 '460798054',
 '460798143',
 '460798293',
 '460798485',
 '460798487',
 '460798493',
 '460798830',
 '460798869',
 '460799196',
 '460799207',
 '460799241',
 '460799311',
 '460799360',
 '460799379',
 '460799392',
 '460799565',
 '460799749',
 '460799789',
 '460799863',
 '460800208',
 '460800357',
 '460800470',
 '460800558',
 '460800611',
 '460800645',
 '460800784',
 '460801050',
 '460801125',
 '460801126',
 '460801142',
 '460801300',
 '460801572',
 '460801608',
 '460801611',
 '460801667',
 '460801747',
 '460802090',
 '460802166',
 '460802483',
 '460802521',
 '460802564',
 '460803005',
 '460803221',
 '460803325',
 '460803396',
 '460803490',
 '460803616',
 '460803671',
 '460803763',
 '460803801',
 '460803998',
 '460804013',
 '460804207',
 '460804470',
 '460804673',
 '460804687',
 '460804800',
 '460804801',
 '460804911',
 '460805049',
 '460805187',
 '460805321',
 '460805327',
 '460805372',
 '460805478',
 '460805704',
 '460805912',
 '460805980',
 '460806364',
 '460806386',
 '460806402',
 '460806412',
 '460806495',
 '460806596',
 '460806816',
 '460806819',
 '460806844',
 '460806974',
 '460806996',
 '460807499',
 '460807553',
 '460807684',
 '460807797',
 '460807927',
 '460808007',
 '460808141',
 '460808232',
 '460808940'}

In [30]:
df = df[df['id'].isin(all_id)]
df

,id,person_info,label,response,query
0,460790679,2024-12-20 15:51:43$%$45V$%$天能$%$72Ah,电池额定电压/额定容量与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
1,460796201,2024-04-09 08:23:10$%$72V$%$超威$%$60Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
2,460802483,2024-04-08 17:59:48$%$60V$%$超威$%$60Ah,非电池相关信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
3,460797429,2022-02-04 13:06:43$%$48V$%$星恒$%$24Ah,非规范电池信息图片|||电池生产日期与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
5,460803801,2019-05-18 10:30:20$%$72V$%$其他品牌:科源$%$70Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
...,...,...,...,...,...
194,460799207,2024-03-09 14:12:14$%$12V$%$超威$%$32Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
195,460794253,2023-03-04 09:22:59$%$60V$%$其他品牌:安耐行$%$80Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
196,460797400,2021-12-13 10:00:23$%$60V$%$其他品牌:劲锐科智能锂电$%$50Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
197,460798293,2024-07-03 12:24:50$%$48V$%$其他品牌:博邦$%$60Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
198,460794561,2024-11-30 14:50:13$%$72V$%$其他品牌:众科$%$60Ah,使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...

In [31]:
df

,id,person_info,label,response,query
0,460790679,2024-12-20 15:51:43$%$45V$%$天能$%$72Ah,电池额定电压/额定容量与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
1,460796201,2024-04-09 08:23:10$%$72V$%$超威$%$60Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
2,460802483,2024-04-08 17:59:48$%$60V$%$超威$%$60Ah,非电池相关信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
3,460797429,2022-02-04 13:06:43$%$48V$%$星恒$%$24Ah,非规范电池信息图片|||电池生产日期与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
5,460803801,2019-05-18 10:30:20$%$72V$%$其他品牌:科源$%$70Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
...,...,...,...,...,...
194,460799207,2024-03-09 14:12:14$%$12V$%$超威$%$32Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
195,460794253,2023-03-04 09:22:59$%$60V$%$其他品牌:安耐行$%$80Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
196,460797400,2021-12-13 10:00:23$%$60V$%$其他品牌:劲锐科智能锂电$%$50Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
197,460798293,2024-07-03 12:24:50$%$48V$%$其他品牌:博邦$%$60Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...
198,460794561,2024-11-30 14:50:13$%$72V$%$其他品牌:众科$%$60Ah,使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...

In [32]:
brand_list = set

In [33]:
df['images'] = df['id'].apply(lambda x: [f'/root/autodl-tmp/context_data/brand_new/{x}.png', f'/root/autodl-tmp/context_data/charge_new/{x}.png'])

/tmp/ipykernel_1374/2431724080.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['images'] = df['id'].apply(lambda x: [f'/root/autodl-tmp/context_data/brand_new/{x}.png', f'/root/autodl-tmp/context_data/charge_new/{x}.png'])

In [34]:
df

,id,person_info,label,response,query,images
0,460790679,2024-12-20 15:51:43$%$45V$%$天能$%$72Ah,电池额定电压/额定容量与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...
1,460796201,2024-04-09 08:23:10$%$72V$%$超威$%$60Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...
2,460802483,2024-04-08 17:59:48$%$60V$%$超威$%$60Ah,非电池相关信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46080...
3,460797429,2022-02-04 13:06:43$%$48V$%$星恒$%$24Ah,非规范电池信息图片|||电池生产日期与填写信息不一致,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...
5,460803801,2019-05-18 10:30:20$%$72V$%$其他品牌:科源$%$70Ah,非电池相关信息图片|||使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46080...
...,...,...,...,...,...,...
194,460799207,2024-03-09 14:12:14$%$12V$%$超威$%$32Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...
195,460794253,2023-03-04 09:22:59$%$60V$%$其他品牌:安耐行$%$80Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...
196,460797400,2021-12-13 10:00:23$%$60V$%$其他品牌:劲锐科智能锂电$%$50Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...
197,460798293,2024-07-03 12:24:50$%$48V$%$其他品牌:博邦$%$60Ah,非规范电池信息图片,"{'电池合规检测': '通过', '电池规格检测': '通过', '品牌检测': '通过',...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...
198,460794561,2024-11-30 14:50:13$%$72V$%$其他品牌:众科$%$60Ah,使用电池规格严重超标，不符合国标要求,"{'电池合规检测': '通过', '电池规格检测': '驳回，使用电池规格严重超标，不符合国...",请针对输入的文本信息和两张图片信息进行相关内容的审核，具体的审核要求如下：\n 1. ...,[/root/autodl-tmp/context_data/brand_new/46079...

In [35]:
df = df[['query', 'response', 'images']]

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
train_df, test_df = train_test_split(df, test_size=0.1)

In [19]:
train_df.to_json('train_aduit.jsonl', lines=True, force_ascii=False, orient='records')
test_df.to_json('test_aduit.jsonl', lines=True, force_ascii=False, orient='records')

In [37]:
import os
import shutil

def remove_brand_from_filenames(directory):
    """
    移除指定目录中PNG图片文件名中的"_brand"部分
    
    参数:
        directory (str): 包含图片文件的目录路径
    """
    # 遍历目录中的所有文件
    for filename in os.listdir(directory):
        # 只处理PNG文件
        if filename.lower().endswith('.png'):
            # 检查文件名中是否包含"_brand"
            if '_brand' in filename:
                # 构建新文件名（去掉"_brand"）
                new_filename = filename.replace('_brand', '')
                
                # 获取完整的旧文件路径和新文件路径
                old_path = os.path.join(directory, filename)
                new_path = os.path.join(directory, new_filename)
                
                # 重命名文件
                try:
                    os.rename(old_path, new_path)
                    print(f"已重命名: {filename} -> {new_filename}")
                except Exception as e:
                    print(f"重命名 {filename} 时出错: {e}")
            else:
                print(f"无需修改: {filename}")

if __name__ == "__main__":
    # 输入包含图片的目录路径
    target_directory = input("请输入包含图片的目录路径: ")
    
    # 检查目录是否存在
    if os.path.isdir('./brand_new/'):
        print(f"开始处理目录: {target_directory}")
        remove_brand_from_filenames(target_directory)
        print("处理完成!")
    else:
        print(f"错误: 目录 '{target_directory}' 不存在")

请输入包含图片的目录路径:  ./brand_new/

开始处理目录: ./brand_new/
无需修改: 460802483.png
无需修改: 460793768.png
无需修改: 460794832.png
无需修改: 460803616.png
无需修改: 460790811.png
无需修改: 460808232.png
无需修改: 460796201.png
无需修改: 460790314.png
无需修改: 460802521.png
无需修改: 460806974.png
无需修改: 460803005.png
无需修改: 460803763.png
无需修改: 460795898.png
已重命名: 460794288_brand.png -> 460794288.png
无需修改: 460806816.png
无需修改: 460796954.png
无需修改: 460796015.png
无需修改: 460802090.png
无需修改: 460694399.png
无需修改: 460801572.png
无需修改: 460800645.png
无需修改: 460807499.png
无需修改: 460801611.png
无需修改: 460798830.png
无需修改: 460794561.png
无需修改: 460795848.png
无需修改: 460807927.png
无需修改: 460797078.png
已重命名: 460792182_brand.png -> 460792182.png
无需修改: 460805704.png
无需修改: 460806386.png
无需修改: 460795691.png
无需修改: 460804801.png
无需修改: 460796007.png
无需修改: 460799863.png
无需修改: 460806596.png
已重命名: 460791881_brand.png -> 460791881.png
无需修改: 460805049.png
无需修改: 460804800.png
无需修改: 460799241.png
无需修改: 460808141.png
无需修改: 460797091.png
无需修改: 460795692.png
无需修改: 460801300.png
无需修改: 460800208.png
无需修改: 460800784.png
无需修改: 460801667.png
无需修改: 460799392.png
无需修改: 460800357.png
无需修改: 460799379.png
无需修改: 460805372.png
已重命名: 460791010_brand.png -> 460791010.png
无需修改: 460796842.png
无需修改: 460804911.png
无需修改: 460806495.png
无需修改: 460796886.png
已重命名: 460791308_brand.png -> 460791308.png
已重命名: 460793319_brand.png -> 460793319.png
无需修改: 460799196.png
无需修改: 460805980.png
无需修改: 460794316.png
无需修改: 460803671.png
无需修改: 460804687.png
无需修改: 460795418.png
无需修改: 460798869.png
已重命名: 460793740_brand.png -> 460793740.png
无需修改: 460794253.png
无需修改: 460802166.png
无需修改: 460799207.png
无需修改: 460790394.png
无需修改: 460796726.png
无需修改: 460800611.png
无需修改: 460795777.png
无需修改: 460803325.png
无需修改: 460796109.png
无需修改: 460807553.png
已重命名: 460791273_brand.png -> 460791273.png
无需修改: 460799789.png
无需修改: 460796492.png
无需修改: 460805187.png
无需修改: 460790988.png
无需修改: 460800558.png
无需修改: 460798293.png
无需修改: 460795013.png
已重命名: 460792269_brand.png -> 460792269.png
无需修改: 460797360.png
无需修改: 460790888.png
无需修改: 460799749.png
无需修改: 460796318.png
已重命名: 460791920_brand.png -> 460791920.png
无需修改: 460801125.png
无需修改: 460804673.png
无需修改: 460802564.png
无需修改: 460796287.png
无需修改: 460794309.png
无需修改: 460804470.png
无需修改: 460795016.png
无需修改: 460799360.png
无需修改: 460801050.png
无需修改: 460797577.png
无需修改: 460806844.png
无需修改: 460798485.png
无需修改: 460798493.png
无需修改: 460798487.png
已重命名: 460793743_brand.png -> 460793743.png
无需修改: 460801126.png
无需修改: 460798054.png
无需修改: 460797429.png
无需修改: 460803490.png
无需修改: 460795028.png
无需修改: 460797400.png
无需修改: 460799565.png
无需修改: 460807797.png
无需修改: 460797063.png
已重命名: 460791592_brand.png -> 460791592.png
已重命名: 460794256_brand.png -> 460794256.png
无需修改: 460800470.png
无需修改: 460795258.png
已重命名: 460791586_brand.png -> 460791586.png
无需修改: 460807684.png
无需修改: 460795066.png
已重命名: 460793985_brand.png -> 460793985.png
无需修改: 460790679.png
无需修改: 460801747.png
无需修改: 460806996.png
无需修改: 460799311.png
无需修改: 460805327.png
无需修改: 460804207.png
无需修改: 460806412.png
无需修改: 460804013.png
无需修改: 460803998.png
已重命名: 460791012_brand.png -> 460791012.png
无需修改: 460808007.png
无需修改: 460805912.png
无需修改: 460798030.png
无需修改: 460801142.png
无需修改: 460797511.png
无需修改: 460795869.png
无需修改: 460803221.png
无需修改: 460796353.png
无需修改: 460806826.png
无需修改: 460801608.png
无需修改: 460803396.png
无需修改: 460795921.png
已重命名: 460793628_brand.png -> 460793628.png
无需修改: 460794747.png
无需修改: 460805321.png
无需修改: 460806402.png
无需修改: 460806364.png
无需修改: 460806819.png
无需修改: 460798143.png
无需修改: 460794180.png
无需修改: 460803801.png
无需修改: 460808940.png
已重命名: 460794212_brand.png -> 460794212.png
无需修改: 460805478.png
无需修改: 460796351.png
无需修改: 460790592.png
无需修改: 460790794.png
处理完成!